// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// Make changes to Manufacturer.swift instead.

/*

	_Manufacturer.swift

	Generated by mogenerator
	Copyright (c) 2015 Norm Barnard

*/

import CoreData

public enum ManufacturerAttributes: String {
    case isNew = "isNew"
    case modificationDate = "modificationDate"
    case name = "name"
    case ownerRecordIdentifier = "ownerRecordIdentifier"
    case recordID = "recordID"
}

public enum ManufacturerRelationships: String {
    case products = "products"
}

@objc public
class _Manufacturer: NSManagedObject {

    // MARK: - Class methods

	public class func mogen_entityName () -> String {
        return "Manufacturer"
    }

    public class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! {
        return NSEntityDescription.entityForName(self.mogen_entityName(), inManagedObjectContext: managedObjectContext);
    }

    // MARK: - Life cycle methods

    public override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext!) {
        super.init(entity: entity, insertIntoManagedObjectContext: context)
    }

    public convenience init(managedObjectContext: NSManagedObjectContext!) {
        let entity = _Manufacturer.entity(managedObjectContext)
        self.init(entity: entity, insertIntoManagedObjectContext: managedObjectContext)
    }

    // MARK: - Properties

    @NSManaged public
    var isNew: NSNumber?

    // func validateIsNew(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var modificationDate: NSDate?

    // func validateModificationDate(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var name: String?

    // func validateName(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var ownerRecordIdentifier: String?

    // func validateOwnerRecordIdentifier(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var recordID: String?

    // func validateRecordID(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    // MARK: - Relationships

    @NSManaged public
    var products: NSSet

}

extension _Manufacturer {

    func addProducts(objects: NSSet) {
        let mutable = self.products.mutableCopy() as! NSMutableSet
        mutable.unionSet(objects as! Set<NSObject>)
        self.products = mutable.copy() as! NSSet
    }

    func removeProducts(objects: NSSet) {
        let mutable = self.products.mutableCopy() as! NSMutableSet
        mutable.minusSet(objects as! Set<NSObject>)
        self.products = mutable.copy() as! NSSet
    }

    func addProductsObject(value: Product!) {
        let mutable = self.products.mutableCopy() as! NSMutableSet
        mutable.addObject(value)
        self.products = mutable.copy() as! NSSet
    }

    func removeProductsObject(value: Product!) {
        let mutable = self.products.mutableCopy() as! NSMutableSet
        mutable.removeObject(value)
        self.products = mutable.copy() as! NSSet
    }

}

