// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// Make changes to Pencil.swift instead.

/*

	_Pencil.swift

	Generated by mogenerator
	Copyright (c) 2015 Norm Barnard

*/

import CoreData

public enum PencilAttributes: String {
    case color = "color"
    case identifier = "identifier"
    case isNew = "isNew"
    case modificationDate = "modificationDate"
    case name = "name"
    case ownerRecordIdentifer = "ownerRecordIdentifer"
    case recordID = "recordID"
}

public enum PencilRelationships: String {
    case inventory = "inventory"
    case product = "product"
}

@objc public
class _Pencil: NSManagedObject {

    // MARK: - Class methods

	public class func mogen_entityName () -> String {
        return "Pencil"
    }

    public class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! {
        return NSEntityDescription.entityForName(self.mogen_entityName(), inManagedObjectContext: managedObjectContext);
    }

    // MARK: - Life cycle methods

    public override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext!) {
        super.init(entity: entity, insertIntoManagedObjectContext: context)
    }

    public convenience init(managedObjectContext: NSManagedObjectContext!) {
        let entity = _Pencil.entity(managedObjectContext)
        self.init(entity: entity, insertIntoManagedObjectContext: managedObjectContext)
    }

    // MARK: - Properties

    @NSManaged public
    var color: AnyObject?

    // func validateColor(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var identifier: String?

    // func validateIdentifier(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var isNew: NSNumber?

    // func validateIsNew(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var modificationDate: NSDate?

    // func validateModificationDate(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var name: String?

    // func validateName(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var ownerRecordIdentifer: String?

    // func validateOwnerRecordIdentifer(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var recordID: String?

    // func validateRecordID(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    // MARK: - Relationships

    @NSManaged public
    var inventory: Inventory?

    // func validateInventory(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var product: Product?

    // func validateProduct(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

}

