// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// Make changes to Product.swift instead.

/*

	_Product.swift

	Generated by mogenerator
	Copyright (c) 2015 Norm Barnard

*/

import CoreData

public enum ProductAttributes: String {
    case isNew = "isNew"
    case modificationDate = "modificationDate"
    case name = "name"
    case ownerRecordIdentifier = "ownerRecordIdentifier"
    case recordID = "recordID"
}

public enum ProductRelationships: String {
    case manufacturer = "manufacturer"
    case pencils = "pencils"
    case syncInfo = "syncInfo"
}

@objc public
class _Product: NSManagedObject {

    // MARK: - Class methods

	public class func mogen_entityName () -> String {
        return "Product"
    }

    public class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! {
        return NSEntityDescription.entityForName(self.mogen_entityName(), inManagedObjectContext: managedObjectContext);
    }

    // MARK: - Life cycle methods

    public override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext!) {
        super.init(entity: entity, insertIntoManagedObjectContext: context)
    }

    public convenience init(managedObjectContext: NSManagedObjectContext!) {
        let entity = _Product.entity(managedObjectContext)
        self.init(entity: entity, insertIntoManagedObjectContext: managedObjectContext)
    }

    // MARK: - Properties

    @NSManaged public
    var isNew: NSNumber?

    // func validateIsNew(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var modificationDate: NSDate?

    // func validateModificationDate(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var name: String?

    // func validateName(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var ownerRecordIdentifier: String?

    // func validateOwnerRecordIdentifier(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var recordID: String?

    // func validateRecordID(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    // MARK: - Relationships

    @NSManaged public
    var manufacturer: Manufacturer?

    // func validateManufacturer(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    @NSManaged public
    var pencils: NSSet

    @NSManaged public
    var syncInfo: SyncInfo?

    // func validateSyncInfo(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

}

extension _Product {

    func addPencils(objects: NSSet) {
        let mutable = self.pencils.mutableCopy() as! NSMutableSet
        mutable.unionSet(objects as Set<NSObject>)
        self.pencils = mutable.copy() as! NSSet
    }

    func removePencils(objects: NSSet) {
        let mutable = self.pencils.mutableCopy() as! NSMutableSet
        mutable.minusSet(objects as Set<NSObject>)
        self.pencils = mutable.copy() as! NSSet
    }

    func addPencilsObject(value: Pencil!) {
        let mutable = self.pencils.mutableCopy() as! NSMutableSet
        mutable.addObject(value)
        self.pencils = mutable.copy() as! NSSet
    }

    func removePencilsObject(value: Pencil!) {
        let mutable = self.pencils.mutableCopy() as! NSMutableSet
        mutable.removeObject(value)
        self.pencils = mutable.copy() as! NSSet
    }

}

