// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// Make changes to SyncInfo.swift instead.

/*

	_SyncInfo.swift

	Generated by mogenerator
	Copyright (c) 2015 Norm Barnard

*/

import CoreData

public enum SyncInfoAttributes: String {
    case lastRefreshTime = "lastRefreshTime"
}

public enum SyncInfoRelationships: String {
    case product = "product"
}

@objc public
class _SyncInfo: NSManagedObject {

    // MARK: - Class methods

	public class func mogen_entityName () -> String {
        return "SyncInfo"
    }

    public class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! {
        return NSEntityDescription.entityForName(self.mogen_entityName(), inManagedObjectContext: managedObjectContext);
    }

    // MARK: - Life cycle methods

    public override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext!) {
        super.init(entity: entity, insertIntoManagedObjectContext: context)
    }

    public convenience init(managedObjectContext: NSManagedObjectContext!) {
        let entity = _SyncInfo.entity(managedObjectContext)
        self.init(entity: entity, insertIntoManagedObjectContext: managedObjectContext)
    }

    // MARK: - Properties

    @NSManaged public
    var lastRefreshTime: NSDate?

    // func validateLastRefreshTime(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

    // MARK: - Relationships

    @NSManaged public
    var product: Product?

    // func validateProduct(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}

}

